### ISSUE TITLE
AMCL cannot publish a pose

### ISSUE THREAD

**Issue by Chandan-kumar-R** [Onicc/navigation2_ignition_gazebo_turtlebot3#1]
How can i resolve this warning ?

![Screenshot from 2024-04-08 12-28-22](https://github.com/Onicc/navigation2_ignition_gazebo_turtlebot3/assets/62261460/6fad9abf-9efa-4fab-9f01-9cec0c150bf7)

**Comment by ymei** [comment]
Use the `2D Pose Estimate` button in RViz, or follow what's in here: https://answers.ros.org/question/401185/amcl-cannot-publish-a-pose-or-update-the-transform-please-set-the-initial-pose/

**Comment by Onicc** [comment]
The issue has been resolved, and no further action is needed at this time. I will close this issue now. 

Feel free to open a new issue if any related concerns arise in the future. 

Thanks for your support!
